### ISSUE TITLE
Command 'TypeScript: Reveal Types' resulted in an error

### ISSUE THREAD

**Issue by Willaiem** [betafcc/ts-reveal-types#1]
Whenever I try to use the TypeScript: Reveal Types command, I get this error:
![obraz](https://user-images.githubusercontent.com/25301582/232457463-8da1b616-02fe-4083-b50e-6a9af25550c9.png)

I tried:
- reinstall the extension
- close and open up the vs code again

**Comment by betafcc** [comment]
interesting, i see why, fixing

**Comment by betafcc** [comment]
missing dependency uncorreclty listed, fixed and published
